# Generated by Django 4.2.5 on 2023-09-13 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_musicas')),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('MPB', 'MPB'), ('POP', 'Pop'), ('ROCK', 'Rock'), ('PAGODE', 'Pagode'), ('OUTROS', 'Outros')], max_length=10)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('dataCriacao', models.DateTimeField(default=datetime.datetime(2023, 9, 13, 17, 51, 22, 957220, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
