# Generated by Django 4.2.5 on 2023-09-13 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='categoria',
            field=models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('OUTROS', 'Outros'), ('MPB', 'MPB'), ('PAGODE', 'Pagode')], max_length=10),
        ),
        migrations.AlterField(
            model_name='musica',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 17, 52, 1, 202882, tzinfo=datetime.timezone.utc)),
        ),
    ]
