# Generated by Django 4.2.5 on 2023-10-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='categoria',
            field=models.CharField(choices=[('POP', 'Pop'), ('PAGODE', 'Pagode'), ('ROCK', 'Rock'), ('OUTROS', 'Outros'), ('MPB', 'MPB')], max_length=10),
        ),
    ]
