# Generated by Django 4.2.5 on 2023-10-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0002_alter_musica_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(choices=[('static/images/avatares/avatar (11).jpg', 'Imagem 11'), ('static/images/avatares/avatar (7).jpg', 'Imagem 7'), ('static/images/avatares/avatar (4).jpg', 'Imagem 4'), ('static/images/avatares/avatar (10).jpg', 'Imagem 10'), ('static/images/avatares/avatar (5).jpg', 'Imagem 5'), ('static/images/avatares/avatar (8).jpg', 'Imagem 8'), ('static/images/avatares/avatar (1).jpg', 'Imagem 1'), ('static/images/avatares/avatar (9).jpg', 'Imagem 9'), ('static/images/avatares/avatar (6).jpg', 'Imagem 6')], default='static/images/avatares/avatar (1).jpg', upload_to='thumb_musicas'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='categoria',
            field=models.CharField(choices=[('POP', 'Pop'), ('OUTROS', 'Outros'), ('ROCK', 'Rock'), ('PAGODE', 'Pagode'), ('MPB', 'MPB')], max_length=10),
        ),
    ]
