# Generated by Django 4.2.5 on 2023-09-13 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0002_alter_musica_categoria_alter_musica_datacriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='categoria',
            field=models.CharField(choices=[('OUTROS', 'Outros'), ('PAGODE', 'Pagode'), ('POP', 'Pop'), ('MPB', 'MPB'), ('ROCK', 'Rock')], max_length=10),
        ),
        migrations.AlterField(
            model_name='musica',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 17, 56, 36, 69962, tzinfo=datetime.timezone.utc)),
        ),
    ]
