# Generated by Django 4.2.5 on 2023-09-15 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0003_alter_musica_categoria_alter_musica_datacriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='categoria',
            field=models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('MPB', 'MPB'), ('PAGODE', 'Pagode'), ('OUTROS', 'Outros')], max_length=10),
        ),
        migrations.AlterField(
            model_name='musica',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 21, 0, 36, 51153, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='MusicaArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='musicas.musica')),
            ],
        ),
    ]
