# Generated by Django 4.2.5 on 2023-09-26 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0004_alter_musica_categoria_alter_musica_datacriacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='categoria',
            field=models.CharField(choices=[('POP', 'Pop'), ('PAGODE', 'Pagode'), ('ROCK', 'Rock'), ('OUTROS', 'Outros'), ('MPB', 'MPB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='musica',
            name='dataCriacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
