# Generated by Django 4.2.5 on 2023-10-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0007_alter_musica_categoria_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='categoria',
            field=models.CharField(choices=[('PAGODE', 'Pagode'), ('POP', 'Pop'), ('MPB', 'MPB'), ('OUTROS', 'Outros'), ('ROCK', 'Rock')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(choices=[('images/avatares/avatar(8).jpg', 'Imagem 8'), ('images/avatares/avatar(4).jpg', 'Imagem 4'), ('images/avatares/avatar(5).jpg', 'Imagem 5'), ('images/avatares/avatar(1).jpg', 'Imagem 1'), ('images/avatares/avatar(10).jpg', 'Imagem 10'), ('images/avatares/avatar(9).jpg', 'Imagem 9'), ('images/avatares/avatar(7).jpg', 'Imagem 7'), ('images/avatares/avatar(11).jpg', 'Imagem 11'), ('images/avatares/avatar(6).jpg', 'Imagem 6')], default='images/avatares/avatar (1).jpg', upload_to='thumb_musicas'),
        ),
    ]
