# Generated by Django 4.2.5 on 2023-10-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0011_alter_musica_categoria_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='categoria',
            field=models.CharField(choices=[('POP', 'Pop'), ('OUTROS', 'Outros'), ('ROCK', 'Rock'), ('PAGODE', 'Pagode'), ('MPB', 'MPB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(choices=[('avatares/avatar(10).jpg', 'Imagem 10'), ('avatares/avatar(6).jpg', 'Imagem 6'), ('avatares/avatar(9).jpg', 'Imagem 9'), ('avatares/avatar(1).jpg', 'Imagem 1'), ('avatares/avatar(11).jpg', 'Imagem 11'), ('avatares/avatar(8).jpg', 'Imagem 8'), ('avatares/avatar(5).jpg', 'Imagem 5'), ('avatares/avatar(4).jpg', 'Imagem 4'), ('avatares/avatar(7).jpg', 'Imagem 7')], default='avatares/avatar(1).jpg', upload_to=''),
        ),
    ]
